// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBicIBaM6rsQ_Fuuo2ILR_8cinIo6R7SdQ',
    appId: '1:499074118231:web:15fb4c6c3e82b661e6e912',
    messagingSenderId: '499074118231',
    projectId: 'legalfactfinder2025',
    authDomain: 'legalfactfinder2025.firebaseapp.com',
    storageBucket: 'legalfactfinder2025.firebasestorage.app',
    measurementId: 'G-9JPCCZ1LK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEpTam2fbXq-BSEt0TplaOy_V0moX_9Fs',
    appId: '1:499074118231:android:56fc6c5a4026ff69e6e912',
    messagingSenderId: '499074118231',
    projectId: 'legalfactfinder2025',
    storageBucket: 'legalfactfinder2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcu0XiGQ6w74gOLPhO2CmyYFWuX3b4zwE',
    appId: '1:499074118231:ios:4290d8401fe04086e6e912',
    messagingSenderId: '499074118231',
    projectId: 'legalfactfinder2025',
    storageBucket: 'legalfactfinder2025.firebasestorage.app',
    iosBundleId: 'com.legalfactfinder.legalfactfinder2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcu0XiGQ6w74gOLPhO2CmyYFWuX3b4zwE',
    appId: '1:499074118231:ios:4290d8401fe04086e6e912',
    messagingSenderId: '499074118231',
    projectId: 'legalfactfinder2025',
    storageBucket: 'legalfactfinder2025.firebasestorage.app',
    iosBundleId: 'com.legalfactfinder.legalfactfinder2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBicIBaM6rsQ_Fuuo2ILR_8cinIo6R7SdQ',
    appId: '1:499074118231:web:227c0cf26a6029f2e6e912',
    messagingSenderId: '499074118231',
    projectId: 'legalfactfinder2025',
    authDomain: 'legalfactfinder2025.firebaseapp.com',
    storageBucket: 'legalfactfinder2025.firebasestorage.app',
    measurementId: 'G-L14THH0JXD',
  );
}
